// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bloom.Data;

#nullable disable

namespace bloom.Migrations.ArSr
{
    [DbContext(typeof(ArSrDbContext))]
    partial class ArSrDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("bloom.Models.ArSrEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DemographicNotes")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Ethnicity")
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<bool?>("HearingLoss")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NativeLanguage")
                        .HasColumnType("longtext");

                    b.Property<string>("ParticipantAccountId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("ReceivingSpeechTherapy")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("ArSr_Enrollments", (string)null);
                });

            modelBuilder.Entity("bloom.Models.ArSrRecording", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SentenceNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("ArSr_Recordings", (string)null);
                });

            modelBuilder.Entity("bloom.Models.ArSrSentenceResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("EditScript")
                        .HasColumnType("longtext");

                    b.Property<int>("Errors")
                        .HasColumnType("int");

                    b.Property<string>("GroundTruth")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Response")
                        .HasColumnType("longtext");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("SentenceNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("ArSr_SentenceResults", (string)null);
                });

            modelBuilder.Entity("bloom.Models.ArSrSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AdministratorNotes")
                        .HasColumnType("longtext");

                    b.Property<int>("AgeMonths")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Percentile")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .HasColumnType("longtext");

                    b.Property<string>("SessionFolder")
                        .HasColumnType("longtext");

                    b.Property<double?>("TotalScore")
                        .HasColumnType("double");

                    b.Property<string>("VideoFilePath")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId");

                    b.ToTable("ArSr_Sessions", (string)null);
                });

            modelBuilder.Entity("bloom.Models.ArSrRecording", b =>
                {
                    b.HasOne("bloom.Models.ArSrSession", "Session")
                        .WithMany("Recordings")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("bloom.Models.ArSrSentenceResult", b =>
                {
                    b.HasOne("bloom.Models.ArSrSession", "Session")
                        .WithMany("SentenceResults")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("bloom.Models.ArSrSession", b =>
                {
                    b.HasOne("bloom.Models.ArSrEnrollment", "Enrollment")
                        .WithMany("Sessions")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("bloom.Models.ArSrEnrollment", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("bloom.Models.ArSrSession", b =>
                {
                    b.Navigation("Recordings");

                    b.Navigation("SentenceResults");
                });
#pragma warning restore 612, 618
        }
    }
}
